LOAD DATA
CHARACTERSET UTF8
  INFILE *
  APPEND
  INTO TABLE OWNERS
  REENABLE
  FIELDS TERMINATED BY ","
  (OWNER_ID, FIRSTNAME, LASTNAME)
BEGINDATA
1,John,Mccarthy
2,Rich,Hickey
3,Edsger W.,Dijkstra
4,Alan,Turing
