LOAD DATA
CHARACTERSET UTF8
  INFILE *
  APPEND
  INTO TABLE OWNERS
  REENABLE
  FIELDS TERMINATED BY ","
  (OWNER_ID "OWNERS_SEQ.NEXTVAL" ,
   FIRSTNAME, LASTNAME)
BEGINDATA
,John,Mccarthy
,Rich,Hickey
,Edsger W.,Dijkstra
,Alan,Turing
